# Generated by Django 3.2.19 on 2024-04-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=16, unique=True)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=255)),
                ('carType', models.CharField(max_length=16)),
                ('carCode', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=255)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=6)),
                ('action', models.CharField(max_length=16)),
                ('generate_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
