# Generated by Django 3.2.19 on 2024-04-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
