# Generated by Django 3.2.19 on 2024-04-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='income',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
