# Generated by Django 3.2.19 on 2024-04-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_auto_20240411_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='income',
            field=models.FloatField(default=0),
        ),
    ]
